### ISSUE TITLE
all scheduled cores encountered errors in user code

### ISSUE THREAD

**Issue by sylvia-science** [JCVenterInstitute/FRmatch#3]
Hello,

I'm trying to run FRmatch on two Seurat objects. I'm using the make_data_object on both objects, but I'm running into the following error:

Error in results["p.value", ] : incorrect number of dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code

I've looked into the FRmatch function and this is definitely happening because the following lines return a results variable with NA values.

results <- pbmcmapply(
    function(samp1,samp2){
      set.seed(subsamp.seed)
      FRtest_subsamp(samp1, samp2, subsamp.size=subsamp.size, subsamp.iter=subsamp.iter, ...)
    },
    paired.datlst.query, paired.datlst.ref,
    mc.cores = numCores)

I think this is happening because my datlst.query variable becomes NA. Is this perhaps because the cluster_membership of my query object is set to ''? I don't have labels for the query object because I'm planning to use the reference object to get them, so that's why I set it up this way. Please let me know if I'm misunderstanding something.

Here's my code for setting up my objects. Thank you very much.
`
######
# Make PC2 reference object
######
data_PanCancer2_HNSCC_small = data_PanCancer2_HNSCC[,1:1000] # Subset to smaller data

dat = transpose(as.data.frame(data_PanCancer2_HNSCC_small@assays[["RNA"]]@counts))
dat$Sample = colnames(data_PanCancer2_HNSCC_small)
dat = dat[,c(ncol(dat),1:(ncol(dat)-1))] # Reorder columns
colnames(dat)[2:ncol(dat)] = rownames(data_PanCancer2_HNSCC_small)

tab = as.data.frame(colnames(data_PanCancer2_HNSCC_small))
colnames(tab) = 'Cell'
tab$cluster_membership = as.character(data_PanCancer2_HNSCC_small$CellType_lev6) 

markers = varFeatures_PC2_HNSCC

sce_PC2<- make_data_object(dat =dat,
                            tab = tab,
                            markers = markers,
                            )
######
# Make HNSCC normal query object
######

dat = transpose(as.data.frame(data_HNSCC@assays[["RNA"]]@counts))
dat$Sample = colnames(data_HNSCC)
dat = dat[,c(ncol(dat),1:(ncol(dat)-1))]
colnames(dat)[2:ncol(dat)] = rownames(data_HNSCC) # Reorder columns to have Sample first

tab = as.data.frame(colnames(data_HNSCC))
colnames(tab) = 'Cell'
tab$cluster_membership = '' # I do not have cell labels for the query

markers = varFeatures_HNSCC

sce_HNSCC <- make_data_object(dat =dat,
                                     tab = tab,
                                     markers = markers)
############

res <- FRmatch(sce.query = sce_HNSCC, sce.ref = sce_PC2,
                           prefix = c("query.", "ref."))

**Comment by yunzhang813** [comment]
Hi. Yes, it is because there is no cluster_membership in the query data, which causes NA in datlst.query. I would suggest you run an initial clustering analysis using Seurat on your query data, which will give you candidate clusters with no label. Then you can use FRmatch_cell2cluster() to match the unlabeled query cells with a reference cluster label. Cells in the same initial cluster will not necessary be matched to the same reference label. The initial clustering is to provide a grouping of cells for FRmatch_cell2cluster() to search in the iteration step.

**Comment by sylvia-science** [comment]
Thank you for your explanation. The code appears to be running now that I added clusters to my query data, but I cannot confirm yet that it works because my local machine does not have enough memory and the server I use has installation issues.
