### ISSUE TITLE
run fails with data extracted from seurat object

### ISSUE THREAD

**Issue by shermas** [JCVenterInstitute/FRmatch#5]
Hey,

I ran the following code using the pbmc3k downloaded from SeuratData:

pbmc = pbmc3k
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
pbmc <- RunUMAP(pbmc, dims = 1:10)

#dat = cell_by_gene_expression
#13945 genes and 15603 cells
#rows - cells, cols-genes
dat.pbmc = t(as.data.frame(pbmc@assays[["RNA"]]@scale.data))
#make sample column
sample_column = as.data.frame(colnames(pbmc))
colnames(sample_column)[1]  <- "Sample"
#merge both into a single dataframe
dat.pbmc = cbind(sample_column, dat.pbmc)

#tab = cell_cluster_labels
tab.pbmc = as.data.frame(colnames(pbmc))
colnames(tab.pbmc) = 'Cell'
tab.pbmc$cluster_membership = pbmc@meta.data$seurat_clusters

#markers = unique_markers
markers.pbmc = FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.85)
markers.pbmc.mod = as.data.frame(markers.pbmc[c('cluster', 'gene')])

sce.pbmc <- make_data_object(dat = dat.pbmc,
                            tab = tab.pbmc,
                            markers = markers.pbmc.mod)

rst.pbmc <- FRmatch(sce.query = sce.pbmc, sce.ref = sce.pbmc, subsamp.size = 10)

The error I'm getting is: 

> rst.pbmc <- FRmatch(sce.query = sce.pbmc, sce.ref = sce.pbmc, subsamp.size = 10)
* Check query data object. 
* Check reference data object. 
* Filtering small clusters: query and reference clusters with less than 5 cells are not considered. 
* Feature selection: 0 out of 0 reference marker genes are presented in the query experiment. 
* Comparing 9 query clusters with 9 reference clusters... 
** Parallel computing with 12 cores. 
** method = subsampling | subsamp.size = 10 | subsamp.iter = 1000 
  |                                                                                                      |   0%, ETA NAError in ade4::mstree(distobj) : 
  NA/NaN/Inf in foreign function call (arg 1)
In addition: Warning message:
In pbmcmapply(function(samp1, samp2) { :
  mc.cores > 1 is not supported on Windows due to limitation of mc*apply() functions.
  mc.core is set to 1.

The code runs fine if I run the FRmatch tutorial with the suggested files.
Can you suggest a fix?

Thanks for the help!

**Comment by yunzhang813** [comment]
Hi there! 

You need to add the following line.
`unique.markers = unique(markers.pbmc.mod$gene)`

Then 
sce.pbmc <- make_data_object(dat = dat.pbmc,
                             tab = tab.pbmc,
                             markers = unique.markers,
                             cluster_marker_info = markers.pbmc.mod)

So that you will see this line when running FRmatch().
> * Feature selection: 723 out of 723 reference marker genes are presented in the query experiment. 

You were not loading the marker genes in the data object before.

**Comment by shermas** [comment]
Thanks so much for the response!
Does this mean that FRmatch only needs a list of markers, but does not need the association between cluster and markers provided? If I understand it correctly, unique() will reduce the dataframe to a list of markers.

**Comment by yunzhang813** [comment]
Yes, to run FRmatch, you just need a list of markers. This info `cluster_marker_info = markers.pbmc.mod` is only used when plotting the cell type barcode using plot_cluster_by_markers().
