### ISSUE TITLE
cell-by-gene expression matrix

### ISSUE THREAD

**Issue by shermas** [JCVenterInstitute/FRmatch#6]
Hi,

When passing the expression matrix which of the matrices do you suggest using (count, log, or scaled)? 

Thanks again

**Comment by yunzhang813** [comment]
If both of your query and reference datasets are generated from the same platform (e.g. 10x), I recommend log-transformed. The function plotDist() will help you to check the data distribution of your query and reference. In principle, the data objects would have similar data distributions for the matching purpose. You may check out our paper https://doi.org/10.1038/s41598-022-14192-z.
